### ISSUE TITLE
Sparkpost 2.0 Library

### ISSUE THREAD

**Issue by matjaz-elumina** [djagya/yii2-sparkpost#11]
Hi,

I see you've switched to the latest Sparkpost library (2.0). I haven't spent much on investigating what's new but I did notice for instance APIResponseException class is missing which should cause this plugin to break.

Just a heads up.

Matjaz

**Comment by djagya** [comment]
Hi @matjaz-elumina,
no, I still use sparkpost lib v1, but I'm planning to switch to v2 soon.
For now while we use v1 all work as intended.
