### ISSUE TITLE
Package sparkpost/php-sparkpost is abandoned

### ISSUE THREAD

**Issue by voskobovich** [djagya/yii2-sparkpost#12]
Hi! When I update packages in my project, I receive the following message

```
egeloen/http-adapter suggests installing doctrine/cache (Allows you to use the cache event subscriber)
egeloen/http-adapter suggests installing ext-http (Allows you to use the PECL adapter)
egeloen/http-adapter suggests installing guzzle/guzzle (Allows you to use the Guzzle 3 adapter)
egeloen/http-adapter suggests installing guzzlehttp/guzzle (Allows you to use the Guzzle 4 adapter)
egeloen/http-adapter suggests installing kriswallsmith/buzz (Allows you to use the Buzz adapter)
egeloen/http-adapter suggests installing nategood/httpful (Allows you to use the Httpful adapter)
egeloen/http-adapter suggests installing rmccue/requests (Allows you to use the Requests adapter)
egeloen/http-adapter suggests installing symfony/stopwatch (Allows you to use the stopwatch http adapter and event subscriber)
egeloen/http-adapter suggests installing tedivm/stash (Allows you to use the cache event subscriber)
egeloen/http-adapter suggests installing zendframework/zendframework1 (Allows you to use the Zend 1 adapter)
egeloen/http-adapter suggests installing zendframework/zend-http (Allows you to use the Zend 2 adapter)
Package egeloen/http-adapter is abandoned, you should avoid using it. Use php-http/httplug instead.
Package sparkpost/php-sparkpost is abandoned, you should avoid using it. Use sparkpost/sparkpost instead.
```

Think it is time to update this package. 
Do you plan to update soon?

**Comment by Borales** [comment]
@voskobovich check your local version ;)

https://github.com/djagya/yii2-sparkpost/blob/master/composer.json#L16
This package uses  `sparkpost/sparkpost` package already.

**Comment by djagya** [comment]
Hi @voskobovich , as @Borales said, check that you have the latest 0.4.1 version in composer.

**Comment by voskobovich** [comment]
@djagya @Borales the last version on packagist is 0.4 https://packagist.org/packages/djagya/yii2-sparkpost
Why?

**Comment by djagya** [comment]
@voskobovich you're right, thanks. Looking into the problem.

**Comment by voskobovich** [comment]
@djagya :)

**Comment by voskobovich** [comment]
How goes the search for a solution?

**Comment by djagya** [comment]
@voskobovich sorry for the long wait, I was confused with versioning. Now you can update to the version `0.4.2`. Let me know if it works

**Comment by voskobovich** [comment]
@djagya bug fixed!

It remains to wait when @sparkpost will fix it
```
Package egeloen/http-adapter is abandoned, you should avoid using it. Use php-http/httplug instead.
```

**Comment by voskobovich** [comment]
@djagya Should I wait for the upgrade sparkport to version 2.0 ?

**Comment by djagya** [comment]
@voskobovich yes, I'm going to do that soon. It requires some significant changes in the extension, so I think it won't be done until the New Year.
