### ISSUE TITLE
Exception when setTo() is empty

### ISSUE THREAD

**Issue by vercotux** [djagya/yii2-sparkpost#2]
When setTo() receives an empty value (such as an empty array []) it will crash with an exception.
I think an exception is too much. It should simply skip sending when the receiver list is empty and perhaps log a warning (yii2-mandrill does this too). Excellent extension otherwise! Thank you for the great work.

**Comment by djagya** [comment]
Hi @vercotux! Thanks, yes, I think you're right.

**Comment by djagya** [comment]
Fixed

**Comment by vercotux** [comment]
Pure awesomeness!
