### ISSUE TITLE
SparkPost API error messages hidden

### ISSUE THREAD

**Issue by vercotux** [djagya/yii2-sparkpost#4]
Hello again!

I found another minor (but quite significant) problem with errors.
Whenever SparkPost rejects a transmission for whatever reason we get an exception.
It all happens on these [two](https://github.com/djagya/yii2-sparkpost/blob/58b44e4a5a1807bf8651c03cca6dde56a52ec435/Mailer.php#L187) [lines](https://github.com/djagya/yii2-sparkpost/blob/58b44e4a5a1807bf8651c03cca6dde56a52ec435/Mailer.php#L188).

The problem is that there are additional strings sent from SparkPost and whenever this happens (for example when quotas are exceeded) those are not included in the final exception.

In addition to `'message'` `APIResponseException` includes some additional and critical information in the following two variables: `'apiMessage'` and  `'apiCode'`. Could you please include them in Yii's log and the final thrown exception?

---

Additionally, while at it, would it be possible to add a setting to allow Mailer to fail gracefully without exceptions? It is quite problematic when the entire application crashes because of something that happened on SparPost's server. Otherwise we need to wrap every single `send()` call in a try-catch block, because you never know when SparkPost might decide to crash our application. Better yet, make it fail gracefully by default and simply `return false` when an exception occurs because of SparkPost to indicate the email was not sent successfully.

**Comment by djagya** [comment]
@vercotux thanks, yeah, I was waiting for https://github.com/SparkPost/php-sparkpost/issues/44 to be fixed, and then just forgot to adjust my code.
Sure, I'll fix that, probably by just throwing the exception we got from sparkpost lib further.

**Comment by djagya** [comment]
And I like your idea about a graceful fail, sounds reasonable.
I don't think it should be the default behavior, but new setting in the component should do the trick.

**Comment by vercotux** [comment]
That sounds good!

**Comment by djagya** [comment]
@vercotux Sorry for a long delay! Does it look good?

**Comment by vercotux** [comment]
That's spot on! I've just tried it out and it looks to be working flawlessly. Really loving this project!
