### ISSUE TITLE
Guzzle 6 dependency

### ISSUE THREAD

**Issue by AnatolyRugalev** [djagya/yii2-sparkpost#5]
Can you please make a Guzzle 6 dependency more configurable? We use Guzzle 5 in our legacy project, so this dependency makes impossible to use your library as is.

See https://github.com/SparkPost/php-sparkpost#setting-up-a-request-adapter

Thank you

**Comment by djagya** [comment]
Hi, @AnatolyRugalev !
Sorry for the delay, yes, i like your idea. I think it's a good thing to be able to use other request adapters.

I'll implement that.

**Comment by AnatolyRugalev** [comment]
@djagya, thank you for support!

**Comment by djagya** [comment]
@AnatolyRugalev done, check the new release 0.3. Thanks for this good idea!

**Comment by AnatolyRugalev** [comment]
@djagya Thank you! Good job!
