### ISSUE TITLE
Sending multiples emails with data

### ISSUE THREAD

**Issue by fasfelipe** [djagya/yii2-sparkpost#6]
Hi @djagya,

I'm writing here like "an issue" but it would be new feature on the API.
I saw that SparkPost it's able to send multiples emails using custom data for each user, like the example below: 

```
{
  "campaign_id": "campaign_name",
  "recipients": [
    {
      "address": "email-1-address@domain1.com.br",
      "metadata": {
        "unique_id": 1212
      },
      "substitution_data": {
        "nome": "Name 1",
        "nova_senha": "axIjU2"
      }
    },
    {
      "address": "email-2-address@domain2.com",
      "metadata": {
        "unique_id": 7862
      },
      "substitution_data": {
        "nome": "Name 2",
        "nova_senha": "asCADe12"
      }
    }
  ],
  "content": {
    "template_id": "template_id_publish"
  }
}
```

I didn't find anything that configure this JSON on Yii2's API, so it would be great to have this feature on Yii2's API. This could improve even more the development on Yii2 saving unnecessary looping.

What do you think about that? Did you solve this case with another solution?

Thanks.

**Comment by djagya** [comment]
Hi,
thanks for your interest in my extension!

Yes, actually I thought about that feature recently, but decided to wait until someone will really need this :)
Agreed, it should be implemented within yii extension, maybe even as a simple proxy layer between you and actual php-sparkpost library.

So yes, i'll implement that soon!

**Comment by fasfelipe** [comment]
Hi @djagya,

Great to see your interesting on this feature. 
I will be waiting for new releases and following this this API.

Great job =]

**Comment by djagya** [comment]
Hi @fasfelipe,
sorry for the long delay.
Please review the changes I made, I think it should be enough.
Let me know if it's ok and I'll close the issue!

**Comment by djagya** [comment]
I'm closing the issue, supposing it's enough.

**Comment by fasfelipe** [comment]
Thanks @djagya.

Sorry for delay, I will test your API next week, but thanks for attention.
