### ISSUE TITLE
Retrieving Sparkpost return or error codes

### ISSUE THREAD

**Issue by marckell** [djagya/yii2-sparkpost#7]
Is there a way to retrieve the return or error codes that a returned from Sparkpost? I see that there is an exception where those details can get logged in line 187 of Mailer.php, but that doesn't seem to be exposed anywhere.

**Comment by djagya** [comment]
Hi, @marckell.

Thanks for the idea,
I added new property where last transmission error is stored (if any): `$mailer->lastError`.

Let me know if it's enough and I'll close issue.

**Comment by djagya** [comment]
I close the issue, supposing it's enough.
