### ISSUE TITLE
Transmission ID

### ISSUE THREAD

**Issue by matjaz-elumina** [djagya/yii2-sparkpost#9]
Hi, 

is it possible that you return Transmission ID (contained in the result from sparkpost) instead of TRUE when message is succesfully sent?

**Comment by matjaz-elumina** [comment]
One other thing I noticed in sendMessage function of Mailer class. Lines 185 and 193 should be: 

`if (ArrayHelper::getValue($result, 'results.total_accepted_recipients') === 0) {`

`if (ArrayHelper::getValue($result, 'results.total_rejected_recipients') > 0) {`

Notice the results "prefix" in getValues function. This is because both of the values are in a sub array with "results" as key.

**Comment by matjaz-elumina** [comment]
Oh, same goes for lines 187 and 195 :)

**Comment by djagya** [comment]
Hi @matjaz-elumina ,
I'll think about returning Transmission ID. It's a good idea but it will be a breaking change, so i'll change major version of the package.

And thanks for reported bugs!

**Comment by djagya** [comment]
@matjaz-elumina I decided to not change return format for `Mailer::sendMessage()`, so it continues to return bool.

But I added few `Mailer` properties that store info about last sent transmission: `$mailer->lastTransmissionId`, `$mailer->sentCount`, `$mailer->rejectedCount`.  
I hope it will be enough for you! Let me know if it's ok and I'll close the issue.

And thanks again for the bugs report, that's really important place for the mailer.

**Comment by matjaz-elumina** [comment]
Great, that will work too. Actually even better. Thanks a lot!

And thank you for sharing this great plugin.

**Comment by matjaz-elumina** [comment]
Just one minor thing. You probably forgot to update the comment:

`* @return bool|string either sent transaction id or 'false' on failure`

**Comment by djagya** [comment]
Oh, right! Thank you!
